import random
import datetime

# --- KONFIGURASI ---
JUMLAH_DATA = 100  # Mau bikin berapa data? Ganti jadi 1000 atau 5000 kalau berani!
FILENAME = "bulk_data.sql"

# --- DATA DUMMY (Bahan Baku) ---
names = ["Budi", "Siti", "Agus", "Dewi", "Rian", "Nina", "Eko", "Fani", "Gilang", "Hani"]
surnames = ["Santoso", "Wijaya", "Kusuma", "Lestari", "Pratama", "Saputra", "Hidayat", "Sari"]
cities = ["Jakarta", "Bandung", "Surabaya", "Yogyakarta", "Medan", "Bali", "Semarang"]
products = [
    (101, 15000000), # Laptop
    (102, 150000),   # Mouse
    (103, 500000),   # Keyboard
    (104, 75000),    # T-Shirt
    (105, 250000)    # Jeans
]
payments = ["Transfer", "E-Wallet", "Cash", "Credit Card"]

def generate_sql():
    print(f"🚀 Memulai generate {JUMLAH_DATA} data dummy...")
    
    with open(FILENAME, "w") as f:
        f.write("-- GENERATED BY PYTHON SCRIPT (Day 6)\n")
        f.write("-- Copy kode ini dan jalankan di SQL Editor\n\n")
        
        # 1. Generate Orders
        f.write("INSERT INTO orders (customer_id, order_date, total_amount, payment_method) VALUES \n")
        
        for i in range(JUMLAH_DATA):
            # Acak Data
            cust_id = random.randint(1, 5) # Asumsi kita punya 5 customer dulu
            prod = random.choice(products)
            amount = prod[1] # Ambil harga
            
            # Acak Tanggal (Dalam 30 hari terakhir)
            days_offset = random.randint(0, 30)
            date_obj = datetime.date.today() - datetime.timedelta(days=days_offset)
            date_str = date_obj.strftime("%Y-%m-%d")
            
            pay = random.choice(payments)
            
            # Format SQL
            row = f"({cust_id}, '{date_str}', {amount}, '{pay}')"
            
            if i < JUMLAH_DATA - 1:
                f.write(row + ",\n") # Koma untuk data selanjutnya
            else:
                f.write(row + ";\n") # Titik koma untuk data terakhir
        
    print(f"✅ Selesai! File '{FILENAME}' berhasil dibuat.")

if __name__ == "__main__":
    generate_sql()
